// menu_shortcuts.h is generated dynamically from menu_shortcuts.h.in
// Modify menu_shortcuts.h.in if you want your changes to stick

// Pens
#define penFine             '.'
#define penMedium           '~'
#define penBold             '#'
#define penBroad            '@'
#define penFineItalic       ','
#define penMediumItalic     '/'
#define penBroadItalic      ';'

// Inks
#define inkWhite            '0'
#define inkDith12           '1'
#define inkDith25           '2'
#define inkDith37           '3'
#define inkDith50           '4'
#define inkDith62           '5'
#define inkDith75           '6'
#define inkDith87           '7'
#define inkBlack            '8'
#define inkRandom           '9'

// Tools
#define modeErase           'e'
#define modePaint           'a'
#define cmdRough            '<'
#define cmdSmooth           '='
#define cmdSmoother         '>'

// Other
#define cmdPref             's'
#define cmdHWPref	    'v'
#define cmdExtPref          'm'
#define cmdAlarmPref	    'q'
#define cmdClear            ':'
#define cmdFill             'f'
#define cmdInvert           'w'
#define cmdSketchUndo       'u'
#define cmdSketchCopy       'c'
#define cmdSketchPaste      'p'
#define cmdSketchCut        'x'
#define cmdRemove           'r'
#define cmdTitle            't'
#define cmdNew              'n'
#define cmdPrevious         '-'
#define cmdNext             '+'
#define cmdNextCategory     '^'
#define cmdText             'z'
#define cmdLine             '_'
#define cmdShape            'o'
#define cmdInsertLast       'l'
#define cmdLock             'j'
#define cmdTransfer         'g'
#define cmdBeam             'b'
#define cmdSend             '?'
#define cmdHelp		    'h'
#define cmdDuplicate	    'y'
#define cmdDetails          'd'
#define cmdPopupCountdownList '!'
#define cmdListView         'i'
#define cmdSecurity         '|'
#define cmdFloodFill        '*'
#define cmdSortByAlarm      '$'
#define cmdSortByPriority   '$'
#define cmdSortByName       '§'
#define cmdToolbar          '%'
